# Generated by Django 5.0.1 on 2024-02-09 14:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='update_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
