# Generated by Django 5.0.1 on 2024-01-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_date_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='پست',
        ),
    ]
