# Generated by Django 5.0.1 on 2024-02-09 14:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
